target 'zhyt' do
  use_frameworks!
  platform :ios, '12.0'
  inhibit_all_warnings!
  
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseStorage'
  pod 'FirebaseDatabase'
  pod 'GoogleSignIn', '5.0.2'

  pod 'Alamofire'
  
  pod 'RxSwift'
  pod 'RxOptional'
  pod 'RxCocoa'

  pod 'LoadableViews'
  pod 'DTCollectionViewManager'
  pod 'DTTableViewManager'
  pod 'Charts'

  pod 'Dip'

  pod 'AppRouter', :git => 'https://github.com/hellbit/AppRouter.git'
  pod 'AppRouter/RxSwift', :git => 'https://github.com/hellbit/AppRouter.git'

  pod 'IQKeyboardManagerSwift'
  pod 'SwiftEntryKit'

end
